### ISSUE TITLE
Delphi 11, Some keys word some dont.

### ISSUE THREAD

**Issue by pnoulis** [Tanikai/vi-delphi#1]
especially all the scrolling commands do not work.
Am i missing something?

**Comment by Tanikai** [comment]
Hi pnoulis,
Sorry to disappoint you, but I've stopped working on this plugin. I think I was in the middle of refactoring the hotkey engine, so this is probably the cause of the issue.

You can try installing the plugin [from the upstream repository](https://github.com/petdr/vide). I got it working with Delphi 10.3 just by creating a .dpk file (see https://github.com/Tanikai/vi-delphi/commit/a7f3fee798661e328cdcfef635eea3f438ec84ee), so you can try creating one for Delphi 11.

**Comment by pnoulis** [comment]
Hi Kai Anter,

Thank you for your reply.
I will try and get it to work .
